# Generated by Django 5.0.6 on 2026-09-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.BigIntegerField(db_index=True, help_text='user_id of the teacher on the Auth Server')),
                ('teacher_name', models.CharField(help_text="Snapshot of the teacher's display name at creation time", max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When the class is scheduled to start (stored in UTC)')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Planned duration in minutes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('room_name', models.CharField(blank=True, help_text='LiveKit room name. Auto-generated on first save.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'classes_liveclass',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['teacher_id', 'scheduled_at'], name='cls_teacher_sched_idx'), models.Index(fields=['status', 'scheduled_at'], name='cls_status_sched_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='liveclass',
            constraint=models.CheckConstraint(check=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='cls_ended_after_started'),
        ),
        migrations.AddConstraint(
            model_name='liveclass',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gte', 1), ('duration_minutes__lte', 600)), name='cls_duration_between_1_and_600'),
        ),
    ]
