# Generated by Django 5.0.6 on 2026-09-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('removed', 'Removed'), ('banned', 'Banned')], db_index=True, default='active', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('join_count', models.PositiveIntegerField(default=0)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='classes.liveclass')),
            ],
            options={
                'db_table': 'classes_classparticipant',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['live_class', 'status'], name='cls_part_class_status_idx'), models.Index(fields=['live_class', 'role'], name='cls_part_class_role_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='classparticipant',
            constraint=models.UniqueConstraint(fields=('live_class', 'user_id'), name='cls_participant_unique_per_class'),
        ),
    ]
