# Generated by Django 5.0.6 on 2026-09-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classparticipant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=16)),
                ('first_joined_at', models.DateTimeField(blank=True, null=True)),
                ('last_left_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('sessions', models.JSONField(default=list)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='classes.liveclass')),
            ],
            options={
                'db_table': 'classes_attendance',
                'ordering': ['first_joined_at'],
                'indexes': [models.Index(fields=['live_class', 'user_id'], name='cls_att_class_user_idx'), models.Index(fields=['user_id'], name='cls_att_user_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('live_class', 'user_id'), name='cls_attendance_unique_per_class'),
        ),
    ]
