# Generated by Django 5.0.6 on 2026-10-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=16)),
                ('text', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System'), ('poll', 'Poll')], default='text', max_length=16)),
                ('visibility', models.CharField(choices=[('class', 'Class'), ('teacher_only', 'Teacher Only')], db_index=True, default='class', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classes.liveclass')),
            ],
            options={
                'db_table': 'classes_classmessage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['live_class', '-created_at'], name='cls_msg_class_created_idx'), models.Index(fields=['live_class', 'visibility'], name='cls_msg_class_vis_idx')],
            },
        ),
    ]
