# Generated by Django 5.0.6 on 2026-10-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(blank=True, default='', max_length=512)),
                ('bucket', models.CharField(blank=True, default='', max_length=255)),
                ('layout', models.CharField(blank=True, default='', max_length=32)),
                ('egress_id', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('active', 'Active'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted')], db_index=True, default='starting', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('playback_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='classes.liveclass')),
            ],
            options={
                'db_table': 'classes_classrecording',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['live_class', '-started_at'], name='cls_rec_class_started_idx'), models.Index(fields=['status'], name='cls_rec_status_idx')],
            },
        ),
    ]
